-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9gzcGcM2ASbFgUe0
udjKrDdLZ0JOm3/jiA2Wz+Va1nmgCgYIKoZIzj0DAQehRANCAASPiifBZXcoAoWk
t+zffZaZKGLIi0zr8vmOxK3Jq1GCnuNFhhzflFIr7GR1OLqJ/LOpbQnyYPFlH3sJ
f9dcZjt9
-----END PRIVATE KEY-----