name: 'Deploy aab to goole store'

on:
  workflow_dispatch:
    branches: [develop]
    inputs:
      message:
        description: 'Message to the QA to help him test the feature.'
        required: false
        default: 'No message left by the developer to help you test :('
      preprod:
        description: 'Do you want to generate a preprod build? (y/n)'
        required: false
        default: 'n'
      prod:
        description: 'Do you want to generate a prod build? (y/n)'
        required: false
        default: 'n'
# if:$ {{ github.event.inputs.preprod == 'y' }}


env:
  SEC_SERVICE_ACCOUNT_JSON: ${{secrets.SERVICE_ACCOUNT_JSON }}
  SEC_ANDROID_KEYSTORE: ${{secrets.ANDROID_KEYSTORE_PROD }}

  SEC_KEYSTORE_PWD: ${{secrets.ANDROID_KEYSTORE_PROD_PASSWORD }}
  SEC_ALIAS: ${{secrets.ANDROID_PROD_KEY_ALIAS }}
  SEC_ALIAS_PWD: ${{secrets.ANDROID_PROD_ALIAS_PWD }}

  SERVICE_ACCOUNT_JSON_PATH: ${{'./android/app/keystore/service_account.json'}}
  ANDROID_KEYSTORE_PATH: ${{'./android/app/keystore/android_keystore.jks'}}
  ARTIFACT_PATH:  ${{ './android/app/build/outputs/bundle/prodRelease/app-prod-release.aab' }}

jobs:
  build_android_aab:
    name: Build Signed Android AAB
    runs-on: ubuntu-latest
    steps:

      #in the folder specified in the release signing configuration
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: './android/app/keystore/'
          encodedString: ${{ env.SEC_ANDROID_KEYSTORE }}
      
      - name: Decode service_account.json
        id: decode_service_account
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'service_account.json'
          fileDir: './android/app/keystore/'
          encodedString: ${{ env.SEC_SERVICE_ACCOUNT_JSON }}

      # Upload Output folder
      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: SERVICE_ACCOUNT_JSON_PATH
          path:  ${{ env.SERVICE_ACCOUNT_JSON_PATH }} 
          retention-days: 3

      # Upload Output folder
      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: download
          path:  ${{ env.ANDROID_KEYSTORE_PATH }} 
          retention-days: 3

