name: 'Android Deployment'

on:
  workflow_dispatch:

env:
  SEC_STORE_PWD: ${{secrets.ANDROID_STORE_PWD }}
  SEC_KEY_ALIAS: ${{secrets.ANDROID_KEY_ALIAS }}
  SEC_KEY_ALIAS_PWD: ${{secrets.ANDROID_KEY_ALIAS_PWD }}

  SERVICE_ACCOUNT_JSON_PATH: ${{'./android/app/deploy/service_account.json'}}
  ARTIFACT_PATH:  ${{ './android/app/build/outputs/bundle/prodRelease/app-prod-release.aab' }}

jobs:
  deploying_to_store:
    name: Deploy aab to store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Insall Java
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      # Validate gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # yarn install
      - name: Run Yarn Install
        run: |
          npm i -g corepack
          yarn install

      # Build and sign APK ("-x test" argument is used to skip tests)
      - name: Build AAB
        run: |
          cd android && ./gradlew :app:bundleRelease -x test
        env:
          KEY_ALIAS: ${{ env.SEC_KEY_ALIAS }}
          KEY_ALIAS_PWD: ${{ env.SEC_KEY_ALIAS_PWD }}
          STORE_PWD: ${{ env.SEC_STORE_PWD }}

      # Upload Output folder
      - name: Upload Output
        uses: actions/upload-artifact@v2
        with:
          name: download
          path:  ${{ env.ARTIFACT_PATH }} 
          retention-days: 3

      #deploy to goole
      - name: Deploy to Play Store
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_JSON_PATH }} 
          packageName: com.teefiapp.production
          releaseFiles: ${{ env.ARTIFACT_PATH }}
          track: internal
